### ISSUE TITLE
META file incomplete

### ISSUE THREAD

**Issue by igarnier** [thierry-martinez/pyml#11]
I think the META file should have a dependency on stdcompat - on my machine at least, linking raises an error stating that the corresponding cmx is not found (using jbuilder). The error doesn not occur once the dep. is added.

**Comment by XVilka** [comment]
Same here:
```
File "_none_", line 1:
Error: No implementations provided for the following modules:
         Stdcompat referenced from /home/user/.opam/default/lib/pyml/pyml.cmxa(Py),
           /home/user/.opam/default/lib/pyml/pyml.cmxa(Pycaml)
```

**Comment by XVilka** [comment]
@igarnier how did you figure the installation then? If I use just "make; make install" for pyml then jbuilder is not able to find it.

**Comment by igarnier** [comment]
Here's my META file in case it helps (in ~/.opam/version/lib/pyml):

description = "py.ml: OCaml bindings for Python"
requires = "unix
            stdcompat"
version = "20171117"
archive(byte) = "pyml.cma numpy.cma"
archive(native) = "pyml.cmxa numpy.cmxa"

**Comment by XVilka** [comment]
Just send a PR then - since it is so easy.

**Comment by thierry-martinez** [comment]
Sorry for the late answer. Thank you @igarnier for the report and the fix, and @XVilka for the ping!

**Comment by XVilka** [comment]
Can be closed I guess?

**Comment by thierry-martinez** [comment]
Yes, I think so. Thanks.
