### ISSUE TITLE
New release in opam repository

### ISSUE THREAD

**Issue by XVilka** [thierry-martinez/pyml#17]
Since there are many useful fixes landed in master. Would be awesome to have an update for the package as well.

**Comment by XVilka** [comment]
So?

**Comment by thierry-martinez** [comment]
Sorry for the delay: https://github.com/ocaml/opam-repository/pull/12082 !
I was hoping to migrate to the dune build system ( https://github.com/thierry-martinez/pyml/issues/13 ) but the migration appeared to be more difficult than I expected.

**Comment by XVilka** [comment]
@thierry-martinez seems that it should be limited to ">=4.03" release, judging by https://travis-ci.org/ocaml/opam-repository/builds/385585579?utm_source=github_status&utm_medium=notification
Speaking about OS X error - sadly I have no idea what it can be, I don't have experience with it.

**Comment by thierry-martinez** [comment]
Thank you for pointing out this. It is a bug in stdcompat: it should be fixed in https://github.com/ocaml/opam-repository/pull/12083 .
