### ISSUE TITLE
printing of python values/exception in the toplevel

### ISSUE THREAD

**Issue by nilsbecker** [thierry-martinez/pyml#2]
it would be good if one could see python values -- that's probably too ill-defined to do. but python expections could be printed as a string in the toplevel. maybe a `pyml.toplevel` package that defines printers for use in utop would be a good addition?

**Comment by thierry-martinez** [comment]
I don’t know about utop. With ocamltop, you may run `#install_printer Py.Object.format` to install a printer for Python values and exceptions.

**Comment by nilsbecker** [comment]
should work the same... and it does! nice. could this printer be mentioned somewhere prominently in the documentation?

**Comment by thierry-martinez** [comment]
I added a section about the custom topl-level in README. Thanks for the suggestion.

**Comment by thierry-martinez** [comment]
Pretty-printers are now installed by default. (No longer need to run `#install_printer` manually.)
