### ISSUE TITLE
Question about Python extension

### ISSUE THREAD

**Issue by zxygentoo** [thierry-martinez/pyml#21]
Trying pyml out for the last couple of days, quite like it.

One question: Is there a way to build Python extensions using pyml? It seems a nice use-case for some Python project to leverage the performance and safety of OCaml (and who doesn't want to write extensions in C/C++ of coz..).

Any one have spent any time on that?

**Comment by swuecho** [comment]
https://blog.janestreet.com/using-python-and-ocaml-in-the-same-jupyter-notebook/

“Calling OCaml from Python”, but do not know how to compile it to .so file.

**Comment by LaurentMazare** [comment]
Building the .so file used for the blog post should be as simple as:

1. Cloning the pythonlib repo, `git clone https://github.com/janestreet/pythonlib.git`
1. Install the potentially missing packages from pythonlib.opam.
1. Run `dune build examples/ocaml.bc.so`.

**Comment by UnixJunkie** [comment]
this issue could be closed, I guess
