### ISSUE TITLE
utop custom toplevel

### ISSUE THREAD

**Issue by nilsbecker** [thierry-martinez/pyml#3]
(from the inria bug tracker) 

it would be great to have a utop custom toplevel built and installed by opam automatically. i just succeeded (i think) in doing that by hand by doing this ugly command in the build directory:

```
echo "let () = UTop_main.main ()" > pyutop_main.ml
echo "Pyutop_main" > pyutop.mltop
ocamlbuild -no-links -tag thread -pkg threads,utop -no-sanitize -no-hygiene -cflags '-I '"$PWD"'' -lflags '-I '"$PWD"' pyml.cma' pyutop.top
```

**Comment by thierry-martinez** [comment]
I would prefer not to have utop as a pyml dependency. I will think about adding a pymlutop package. Thank you for the suggestion!

**Comment by nilsbecker** [comment]
yes, i agree that the dependency would be unnecessary. does utop not have optional dependencies? so that if utop is present, extra build actions can be triggered?

**Comment by nilsbecker** [comment]
sorry, i meant 'does opam not support optional dependencies'

**Comment by thierry-martinez** [comment]
Yes, you’re right: `utop` is now an optional dependencies, and a `pymlutop` executable is installed if `utop` is available. Thanks.

**Comment by nilsbecker** [comment]
very cool!
