### ISSUE TITLE
Memory leak in numpy_stubs.c?

### ISSUE THREAD

**Issue by igarnier** [thierry-martinez/pyml#30]
Hi, I wonder whether there is a memory leak in `numpy_stubs.c` in the function `parray_of_bigarray_wrapper`. This function calls `PyArray_New` on the data underlying the given bigarray. I'm afraid that the Python runtime frees this data along the Numpy array wrapper when the Python GC kicks in. The following post suggests to use `PyArray_SimpleNewFromData` instead: https://stackoverflow.com/questions/12582875/c-array-to-pyarray

I had arrays suddenly filled with nonsense after executing unrelated functions. My temporary fix is to copy everything that goes/comes from numpy.
I think that beside the Python GC there is an additional issue for OCaml float arrays wrapped to numpy, since the OCaml GC can move them (correct me if I'm mistaken).

**Comment by thierry-martinez** [comment]
Sadly, you are probably right for both bad behaviours regarding Python and OCaml GCs. However, I am not sure how to fix them. In particular, `PyArray_SimpleNewFromData` is just a macro that expands into a call to `PyArray_New`, with the same kinds of arguments that are used in `numpy_stubs.c`. I will try to find a way to fix these problems quickly, but I need to think more about this: sorry for the delay.

**Comment by thierry-martinez** [comment]
Regarding the possibility that Python would free the bigarray data when collecting the numpy array, it seems that `NPY_ARRAY_OWNDATA` flag is *not* set by default by `PyArray_New` (or, more precisely, by the auxiliary function `PyArray_NewFromDescr_int`) when `data` is not `NULL`. Therefore, if I understand correctly the semantics of this flag, the data should be freed by Python.

**Comment by thierry-martinez** [comment]
However, I think you are right that what is done with float arrays is unsafe: I am still thinking about a fix for that, but meanwhile, you should not use them and use bigarrays instead. Do you experience memory corruption when using bigarrays? It will be great if you can give a code sample!

**Comment by igarnier** [comment]
Thanks a lot for your quick answer. Yes, I experienced memory corruption using bigarrays. The code is rather big but the part that directly calls the `Numpy.of_bigarray` and etc is there : https://gitlab.com/nomadic-labs/tezos/blob/9a775a73ee4961d9d6bacec4822f4c19ae096026/src/proto_alpha/lib_protocol/benchmark/micro/matrix.ml
I had no problem with this code up until after some refactoring, where I noticed that the contents of a matrix would suddenly become nonsense after executing an unrelated (but Pyml-using) function. My hypothesis was that Python's gc got triggered at that point and that Python freed the bigarray data (allocated on OCaml side) resulting in memory corruption.
I fixed (?) the problem in the current version of the code by making a copy of every bigarray going to/from numpy. This code is not very performance sensitive so it's ok.

As you say, letting two GCs interact is a tricky matter!

**Comment by thierry-martinez** [comment]
I was able to reproduce memory corruption when floatarrays are moved by OCaml GC, and the commit 3632bdf should fix that. Thanks a lot for having reported this!
I am still trying to reproduce the memory corruption using bigarrays.

**Comment by igarnier** [comment]
Great ! Let's close this issue then, I'll reopen it if need be :)
