### ISSUE TITLE
Failure to load in `ocaml-jupter`

### ISSUE THREAD

**Issue by mseri** [thierry-martinez/pyml#35]
It used to work fine. Now it fails as follows:
```
#require "matplotlib"

/Users/mseri/.opam/4.08.1/lib/base/caml: added to search path
/Users/mseri/.opam/4.08.1/lib/base/caml/caml.cma: loaded
/Users/mseri/.opam/4.08.1/lib/base/shadow_stdlib: added to search path
/Users/mseri/.opam/4.08.1/lib/base/shadow_stdlib/shadow_stdlib.cma: loaded
/Users/mseri/.opam/4.08.1/lib/sexplib0: added to search path
/Users/mseri/.opam/4.08.1/lib/sexplib0/sexplib0.cma: loaded
/Users/mseri/.opam/4.08.1/lib/base: added to search path
/Users/mseri/.opam/4.08.1/lib/base/base.cma: loaded
/Users/mseri/.opam/4.08.1/lib/ocaml/unix.cma: loaded
/Users/mseri/.opam/4.08.1/lib/seq: added to search path
/Users/mseri/.opam/4.08.1/lib/result: added to search path
/Users/mseri/.opam/4.08.1/lib/result/result.cma: loaded
/Users/mseri/.opam/4.08.1/lib/uchar: added to search path
/Users/mseri/.opam/4.08.1/lib/stdcompat: added to search path
/Users/mseri/.opam/4.08.1/lib/stdcompat/stdcompat.cma: loaded
/Users/mseri/.opam/4.08.1/lib/pyml: added to search path
/Users/mseri/.opam/4.08.1/lib/pyml/pyml.cma: loaded
Error: The external function `Python3_PyUnicode_AsUCS4Copy_wrapper' is not available
```

**Comment by mseri** [comment]
I take it back, it does not depend on the ocaml version It seems to fail now in both the latest versions (the only ones I had tried). I am surprised because I used `matplotlib`'s package in `ocaml-jupyter` in the past, and it started failing only recently.

@LaurentMazare does it work for you?

**Comment by LaurentMazare** [comment]
@mseri `ocaml-matplotlib` works fine for me via `pyml` with 4.08.1, though I haven't run it in an `ocaml-jupyter` kernel in this case.
Could you try the `ocaml-matplotlib` examples outside of `ocaml-jupyter` ?
From your error message this looks more like the C part of pyml not being loaded properly, e.g. something similar to the following although it's pretty hard to tell from this error message only.
https://discuss.ocaml.org/t/how-to-load-c-object-files-in-the-toplevel-ocaml-or-utop/2214

**Comment by thierry-martinez** [comment]
The error is interesting: it seems that the `libpython.so` that is tried to being loaded has a different API than expected, and I wonder how I can make `pyml` compatible with this API. If you run `Py.initialize ~verbose:true ()`, you will know the path to the library that is being loaded (with the message `Trying to load ...`): if you can tell me which Python version this file corresponds to and from which distribution it comes from, these informations will help me a lot! Thanks.

**Comment by mseri** [comment]
Thans @thierry-martinez and @LaurentMazare. The output I get from

is
```
Py.initialize ~verbose:true ();;
Temporary set PYTHONPATH=":/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python27.zip:/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7:/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin:/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac:/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages:/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk:/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old:/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload:/Library/Python/2.7/site-packages:/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python:/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC".
Trying to load "libpython2.7m.dylib".
Failed: "Library not found".
Temporary set PYTHONHOME="/usr/bin/../lib/..".
Trying to load "/usr/bin/../lib/libpython2.7m.dylib".
Failed: "Library not found".
Trying to load "libpython2.7.dylib".
Temporary set PYTHONHOME="/usr/bin/..".
- : unit = ()
```

Is it ignoring my `python3` installation, and only considering the system `python2.7`. Is there a way to force it to use `python3`?

**Comment by mseri** [comment]
If it helps I have `Python 3.7.4` installed with homebrew: `/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python`

**Comment by mseri** [comment]
I have the same failure on the jupyter notebook environment in `https://hub.ocamllabs.io`. In that case `pymltop` gives
```
# Py.initialize ~verbose:true ();;
Temporary set PYTHONPATH=":/usr/lib/python2.7:/usr/lib/python2.7/plat-x86_64-linux-gnu:/usr/lib/python2.7/lib-tk:/usr/lib/python2.7/lib-old:/usr/lib/python2.7/lib-dynload:/usr/local/lib/python2.7/dist-packages:/usr/lib/python2.7/dist-packages".
Temporary set PYTHONHOME="/usr/lib/x86_64-linux-gnu/..".
Trying to load "/usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0".
- : unit = ()
```

**Comment by LaurentMazare** [comment]
If it's possible in your use case, you can specify some major version number when calling `Py.initialize`, you can also point it directly to the proper python binary with the `?interpreter` flag.
Alternatively, you can set your `PATH` environment variable to start with the directory with the python binary that you would like to use (you may also be able to use `PYTHONHOME` or `PYTHONPATH` although I'm not sure whether these would work).

**Comment by mseri** [comment]
I had already tried both approaches, attempting all the path variables as you suggest after I had a look at pyml sources. Unfortunately without success (still loads python2.7 in pymltop and fails with jupyter with the same error). I'll try to dig more. If I find a solution or a workaround I will let you know.

I was pressing into it mostly because I wanted to add a demo using matplotlib from an ocaml notebook interactively, and found out that my previous notebook does no longer work. I'll make a static demo, but I want to figure it out at a certain point.
