### ISSUE TITLE
New opam release

### ISSUE THREAD

**Issue by LaurentMazare** [thierry-martinez/pyml#45]
Hi @thierry-martinez 
Would you be able to make a new opam release of pyml to include all the newly released bits? This would be useful as we have some opam package that rely on some of the new features. Let me know if there is any way for me to help.

**Comment by thierry-martinez** [comment]
Thank you for suggesting it! I just tagged the new release 20200115 and there is an ongoing https://github.com/ocaml/opam-repository/pull/15844 for this release.

**Comment by LaurentMazare** [comment]
Excellent, thanks!
