### ISSUE TITLE
Failed to build on macos, missing stdcompat.h

### ISSUE THREAD

**Issue by haochenx** [thierry-martinez/pyml#48]
Hi, I was trying to build the top-level with `make pymltop` but got the following error:

```
ocamlfind ocamlc -package stdcompat -c pyml_stubs.c -o pyml_stubs.o
pyml_stubs.c:15:10: fatal error: 'stdcompat.h' file not found
#include <stdcompat.h>
         ^~~~~~~~~~~~~
1 error generated.
make: *** [pyml_stubs.o] Error 2
```

`opam install pyml` worked fine and I had `stdcompat` installed via opam.

OCaml version is `4.07.1` and I'm trying the master branch. Any clue to a solution?

**Comment by haochenx** [comment]
Actually I just realized that `opam install pyml` automatically installs `pymltop` and `pymlutop` so for practical usage it's fine for me. But I still want to know is there any clue to solve the problem so I could build the source code.

**Comment by thierry-martinez** [comment]
It looks like your version of the `stdcompat` package is too old: `stdcompat.h` is only installed with the last version (13) of `stdcompat` (and `master`, of course). This requirement is specified in the `dune-project` file and should be enforced by opam, but it could be unchecked if you compile pyml's master branch manually.

**Comment by haochenx** [comment]
That was it! Thanks a lot. (Sorry for the late reply. It seems that my previous reply wasn’t gotten sent successfully.)
