### ISSUE TITLE
 Support Python 3.9: internal PyImport_Cleanup() function removed in Python 3.9

### ISSUE THREAD

**Issue by vstinner** [thierry-martinez/pyml#49]
Building coccinelle with Python 3.9 fails on linking since PyImport_Cleanup() function has been removed from libpython in Python 3.9:
https://bugzilla.redhat.com/show_bug.cgi?id=1791765#c3

coccinelle bundles pyml in bundles/pyml/.

I removed PyImport_Cleanup() function from libpython on purpose: you should really not call it.  See [What's New in Python 3.9](https://docs.python.org/dev/whatsnew/3.9.html#removed):

> The C function PyImport_Cleanup() has been removed. It was documented as: "Empty the module table. For internal use only." (Contributed by Victor Stinner in bpo-36710.)

The issue was already reported on cocci mailing list last January:
I mentioned it here: https://systeme.lip6.fr/pipermail/cocci/2020-January/006785.html

I wrote a PR to remove PyImport_Cleanup() wrapper: it doesn't seem to be used by Coccinelle anymore.

I first reported the issue to coccinelle: https://github.com/coccinelle/coccinelle/issues/189

**Comment by vstinner** [comment]
PyImport_Cleanup() wrapper was added by

```
commit 72e486e7aa327461ecce06ba4bfa121d3872a544
Author: Thierry Martinez <martinez@nsup.org>
Date:   Thu Jun 9 18:26:08 2016 +0200

    - Bindings for Python 2 and Python 3
    
    - Tests for initialization, class definition, callback and data wrapping
```

**Comment by thierry-martinez** [comment]
The function has been removed from the high level interface, and is marked as optional in the low level interface. Thank you very much for the report!

**Comment by vstinner** [comment]
Did you see my https://github.com/thierry-martinez/pyml/pull/50 ? I modified more code than https://github.com/thierry-martinez/pyml/commit/8b26fdb9f60c3a66b58f2ecc1b2136a833f55612

It was never safe to call PyImport_Cleanup() explicitly. I suggest to remove it from all Python versions.

**Comment by thierry-martinez** [comment]
I prefer not to break retrocompatibility for free. pyml only provide bindings: it is the library user's responsibility not to call unsafe functions. Thanks fro the report.

**Comment by vstinner** [comment]
Ok, thanks.
