### ISSUE TITLE
segfault on Run.eval

### ISSUE THREAD

**Issue by nilsbecker** [thierry-martinez/pyml#5]
i do this:
```
open Py;;
initialize ();;
Run.eval "3.";;
Run.eval "3. ";;
```
the first eval gives a `pyobject`, the second segfaults.

os x 10.11, python 2.7.11 anaconda, ocaml 4.04.0

**Comment by thierry-martinez** [comment]
I cannot reproduce the bug, even with anaconda. Is the bug observed with master?

**Comment by nilsbecker** [comment]
i just did opam update and have the newest master now. for some reason i do not get the segfault anymore! great!
