### ISSUE TITLE
Warning 58: no cmx file was found in path for module Numpy, and its interface was not compiled with -opaque

### ISSUE THREAD

**Issue by jonathan-laurent** [thierry-martinez/pyml#55]
I am getting the following warning when compiling code that uses the `Numpy` module from `pyml`:
```
File "_none_", line 1:
Warning 58: no cmx file was found in path for module Numpy, and its interface was not compiled with -opaque
```
This happens for example when compiling the [A2C example from ocaml-torch](https://github.com/LaurentMazare/ocaml-torch/blob/master/examples/reinforc.ement-learning/a2c.ml).

**Comment by thierry-martinez** [comment]
Should be fixed now. Thank for the report!
