### ISSUE TITLE
Support python on macOS installed with brew

### ISSUE THREAD

**Issue by andersthune** [thierry-martinez/pyml#56]
These bindings do not seem to work on macOS with Python installed by brew at the moment: pyml is unable to locate the libpython file.

Running `Py.initialize ()` produces the error:

```
Fatal error: exception Failure("Py.find_library: unable to find the Python library [libpython3.8m.dylib returned Library not found] [/usr/local/bin/../lib/libpython3.8m.dylib returned Library not found] [libpython3.8.dylib returned Library not found] [/usr/local/bin/../lib/libpython3.8.dylib returned Library not found]")
```

The path to the shared library can be found using `python3-config --ldflags`:

```
>> python3-config --ldflags

-L/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/config-3.8-darwin -ldl -framework CoreFoundation
```

Would it be possible to make pyml search for the library path using this command?

**Comment by UnixJunkie** [comment]
Maybe you should send a full test script to reproduce your problem.
