### ISSUE TITLE
play nice with conda env

### ISSUE THREAD

**Issue by nilsbecker** [thierry-martinez/pyml#59]
the anaconda python distribution probides a convenient system to manage virtual environments. after configuring an environment `myenv`, `conda activate myenv` configures the shell to use that. e.g. `type python` then gives the path to the python executable corresponding to the env. 

however, when i start `pymlutop` and then try `Py.initialize ()` this fails because it looks for the `libpython....dylib` library that corresponds to the base environment, not the currently activated one. i don't quite know why? is the shell path not used as the first search option to locate the relevant `python` executable?

**Comment by thierry-martinez** [comment]
Sorry for the delay and thank you for the report! This should be fixed now.
