### ISSUE TITLE
attach to a running python instance

### ISSUE THREAD

**Issue by nilsbecker** [thierry-martinez/pyml#6]
is it possible to initialize pyml to a running python/ipython process? that would be useful for interactive work. if not, is there a workaround to produce one utop and one ipython who are linked via pyml?

**Comment by thierry-martinez** [comment]
No, I don’t think it is possible, it is one use case for which the lymp package you mentioned is better suited (because lymp is always connected by design to another python process, even if I don’t know if it allows you to choose which process to connect to).
