### ISSUE TITLE
Numpy.to_bigarray causes a segfault when passed a python object with the wrong type

### ISSUE THREAD

**Issue by jonathan-laurent** [thierry-martinez/pyml#61]
The following code causes a segfault:
```ocaml
let () =
  Py.initialize;
  Numpy.to_bigarray Float64 C_layout Py.none
```
Would it be possible for `Numpy.to_bigarray` to raise an exception instead (as is done by`Py.Int.to_int` for example)?

**Comment by thierry-martinez** [comment]
Thank you very much for reporting! This should be fixed now.

**Comment by jonathan-laurent** [comment]
Thanks for your answer!

However, your fix only applies to the case where `None` is passed and indeed, the code below still segfaults:

```ocaml
let () =
  Py.initialize;
  Numpy.to_bigarray Float64 C_layout (Py.Int.of_int 2)

```

Would there be a way for `Numpy.to_bigarray` to check whether the passed object is indeed a numpy array?

**Comment by thierry-martinez** [comment]
Oops! Sorry for that. Done!
