### ISSUE TITLE
Pyml does not build in byte mode

### ISSUE THREAD

**Issue by nicoTolly** [thierry-martinez/pyml#62]
When compiling to bytecodes, pyml fails to link with :
```
      ocamlc py_bug.bc (exit 2)
(cd _build/default && /home/nico/.opam/default/bin/ocamlc.opt -w @1..3@5..28@30..39@43@46..47@49..57@61..62-40 -strict-sequence -strict-formats -short-paths -keep-locs -g -o py_bug.bc /home/nico/.opam/default/lib/ocaml/unix.cma /home/nico/.opam/default/lib/stdcompat/stdcompat.cma /home/nico/.opam/default/lib/pyml/pyml.cma /home/nico/.opam/default/lib/pyml/numpy.cma .py_bug.eobjs/byte/dune__exe__Py_bug.cmo)
/usr/bin/ld: cannot find -lnumpy_stubs
/usr/bin/ld: cannot find -lpyml_stubs
/usr/bin/ld: cannot find -lstdcompat__stubs
collect2: error: ld returned 1 exit status
```

Dune file : 
```
(executable
 (name py_bug)
 (modes byte)
 (libraries pyml)
 )
```
And a dummy ml file : 
```
let () = print_endline "Hello World"
```
Everything is fine when we compile to native code.

**Comment by thierry-martinez** [comment]
(Cross-posted on discuss.ocaml.org: https://discuss.ocaml.org/t/dune-fails-to-compile-my-library-with-pyml/7441/4?u=thierry-martinez)
Sorry for not having answered earlier and thank you very much for reporting! The problem appears to be that, when building your executable, ocamlc calls ld with the options -L. -lpyml_stubs (and the same pattern for the other libraries): these are the options passed to ocamlc for building pyml.cma (pyml's Makefile line 116: -cclib "-L. -lpyml_stubs"). Obviously, the -L. is wrong and should be something like -L~/.opam/4.12/lib/pyml, but I don’t know how to fix that properly: when building pyml.cma, pyml's Makefile doesn’t know where ocamlfind will install it (and doesn’t even know if it will be installed or used in place, for example to run test files, for which -L. is the correct option to pass). Any ideas? I will continue to look for a solution…

**Comment by nicoTolly** [comment]
Thanks for the (actually very quick) answer :) 

As for your question, I looked up into ocamlfind documentation and there is actually a neat command that tells in which directory packages are found and (I guess) installed : 

ocamlfind printconf path

Which prints on my system : 
/home/nico/.opam/conv_mm/lib (conv_mm is my current switch)

Maybe this could come in handy ?

**Comment by thierry-martinez** [comment]
dune is now the default build system (14175333079b01ec496c69204aad53d6e0ae7c95) and should solve this issue.

**Comment by thierry-martinez** [comment]
Thank you very much for reporting and sorry for having left this project dormant for such a long time.
