### ISSUE TITLE
Call function with positional argument

### ISSUE THREAD

**Issue by sloboegen98** [thierry-martinez/pyml#66]
I have a function from python library with some arguments can be passed only as named:

```python
def foo(x, *, y=None, z=None):
    ...
```
Could you help me what should I write to make a call `foo(41, z=42)`?

And one more related question: if there is a dict (`Py.Dict.of_bindings_string  [ "x", Py.Int.of_int 41; "z", Py.Int_of_int 42 ]`) is it possible to make a call `foo(**dict)` on the OCaml side?

**Comment by thierry-martinez** [comment]
Sorry for the very long delay for this answer. Here is an example which should answer both of your questions. In general, `Py.Callable.to_function_as_tuple_and_dict` converts a Python function to an OCaml function taking a Python tuple for positional arguments and a Python dictionary for named arguments. There are then specialized versions, such as `Py.Module.get_function_with_keywords`, which take OCaml `arrays` of arguments and/or associative lists of keywords instead.

```
let () = Py.initialize ~version:3 ()

let () =
  let compile =
    Py.Module.get_function (Py.Module.builtins ()) "compile" in
  let example = Py.Import.exec_code_module "example"
    (compile [| Py.String.of_string {|
def foo(x, *, y=None, z=None):
  print(x, y, z)
    |}; Py.String.of_string "example"; Py.String.of_string "exec" |]) in
  ignore (Py.Module.get_function_with_keywords example "foo"
    [| Py.Int.of_int 41 |] ["z", Py.Int.of_int 42 ]);
  let dict =
    Py.Dict.of_bindings_string ["x", Py.Int.of_int 41; "z", Py.Int.of_int 42] in
  ignore
    (Py.Callable.to_function_as_tuple_and_dict (Py.Module.get example "foo")
      Py.Tuple.empty dict)
 ```

**Comment by sloboegen98** [comment]
Thanks!
