### ISSUE TITLE
handle more ocaml-config:system variants

### ISSUE THREAD

**Issue by olafhering** [thierry-martinez/pyml#68]
With commit 14175333079b01ec496c69204aad53d6e0ae7c95 only `linux|unix`, `cygwin` and `darwin` are handled.

I get a zoo of variants, depending on the rpm target architecture:

````
aarch64 has system: linux
armv6l has system: linux_eabihf
armv7l has system: linux_eabihf
i586 has system: linux_elf
ppc64 has system: elf
ppc64le has system: elf
riscv64 has system: linux
s390x has system: elf
x86_64 has system: linux
````

**Comment by thierry-martinez** [comment]
Thank you very much for your detailed report. I would not have been able to list so many variants myself. It should be fixed now.

**Comment by gdt** [comment]
How is this supposed to work on operating systems not yet encountered, like NetBSD?  It seems that whatever needs to know OS should instead be doing feature tests.

**Comment by gdt** [comment]
On NetBSD, system values are:
```
amd64, earmv7hf-el: netbsd
i386: bsd_elf
```

So this seems  troubled in ocaml.
