### ISSUE TITLE
numpy arrays

### ISSUE THREAD

**Issue by nilsbecker** [thierry-martinez/pyml#7]
i tried out the Array.of_array function:
```
let py = Module.main ();;
let oa = Array.of_array (Float.of_float) (Float.to_float) [|2.;3.|];;
let _ = Module.set py "oa" oa;;
```
then i started an interactive Ipython session where indeed oa exists. i can index it with oa[0] etc. however it is shown as `<?.array instance at 0x10189aef0>`, not pretty-printed and i can't make an np.array out of it via `np.array(oa)` . likewise `oa?` gives exceptions.

i guess some or all of this is expected. but how can i make a numpy array out of this somewhat mysterious array object?

**Comment by nilsbecker** [comment]
ah, `np.array(list(oa))` works. is that the proper way?

**Comment by nilsbecker** [comment]
ah, but then i imagine the data are no longer shared with the original array...

**Comment by nilsbecker** [comment]
hm, np.frombuffer also does not cut it. another question: i was able to modify elements in the original array from ocaml, by doing first
```
let oca = [|3.;4.|];;
let oa = Py.Array.of_array (Float.of_float) (Float.to_float) oca;;
```
and then setting oca elements. (incidentally, the module names in pyml mean that open Py is a bad idea....)

is there a way to get the ocaml array back from `oa`? i.e. if i did not keep a reference on oca, can i get an array back?

**Comment by thierry-martinez** [comment]
These mysterious arrays are objects that have an array interface (indexed access, length information, iterable), but unfortunately they cannot be used as numpy array without being copied (as you already noticed). They are now well pretty-printed.

I just added a function Py.Array.numpy that transforms float arrays into numpy arrays (without copy). Note that you must keep a reference to the float array in order to the underlying memory not to be freed for now (I hope to be able to do that in a safer way, but I don’t see how as for now).

There is no way to get the ocaml array back. For the "mysterious" arrays, you can adapt the code in py.ml to add a field with a capsule to your array, but it looks too ad-hoc to me for adding that in py.ml. For numpy array, as I said, you _must_ keep the reference if you don't want to segfault!

**Comment by nilsbecker** [comment]
hi, i tried Py.Array.numpy but have not succeeded yet. how must i call it? i keep getting `numpy.ndarray: unhashable type` errors. i tried importing numpy first, and also calling Py.Array.numpy_api () first.

**Comment by nilsbecker** [comment]
sometimes also : `Py.E (<type 'exceptions.ImportError'>, No module named core.multiarray)`

**Comment by thierry-martinez** [comment]
What is displayed in a Python session if you run:
```
import numpy
numpy.version.version
```

I get 1.12.0: if you use a former version, I probably have to adapt my code. Does the command `import numpy.core.multiarray` succeed if you run it in a Python session?

Did you try after setting PYTHONHOME and DYLD_LIBRARY_PATH as for the ipython bug?

**Comment by nilsbecker** [comment]
i am using 1.11.2. import numpy.core.multiarray succeeds. 

however, i may have forgotten to set the environment! will check in a second

**Comment by nilsbecker** [comment]
oh, ok now i get something! sorry for the confusion. will report back if i run into other problems, but for now i think i was missing the environment variables.

**Comment by nilsbecker** [comment]
ok: without having the printer Py.Object.format installed, i get a Pytypes.pyobject back. with printer installed, i get an 'unhashable type' exception

**Comment by nilsbecker** [comment]
hmm. also without the printer, when i do this:
```
Py.initialize()
let aa = Py.Array.numpy [|1.|]
Py.Run.ipython ()
```
i get an exception (which i cannot read without the printer..)

**Comment by nilsbecker** [comment]
this happens also if i (as i should?) first define `let a = [|1.|]` and then `let aa = Py.Array.numpy a`.

**Comment by nilsbecker** [comment]
maybe i'm doing it wrong: could you provide some test commands that should work, including proper order of initialization etc?

**Comment by thierry-martinez** [comment]
Your usage was correct. Sorry for the delay: it should now be fixed. Note that the garbage collection bug is fixed as well: you no longer need to keep a reference to the OCaml array. You can even get the OCaml array back from a Numpy array provided it was created from OCaml with Py.Array.numpy_get_array.

**Comment by nilsbecker** [comment]
cool! i tried it out and the new ocamlarray is a subtype of numpy.ndarray. this looks promising.
