### ISSUE TITLE
`nix` derivation

### ISSUE THREAD

**Issue by quinn-dougherty** [thierry-martinez/pyml#73]
What has to happen to get this on `nixpkgs`?

**Comment by UnixJunkie** [comment]
@quinn-dougherty isn't there an opam2nix thing?
https://github.com/timbertson/opam2nix

Disclaimer: I haven't tried it.

**Comment by jtojnar** [comment]
It has been in Nixpkgs for a while now: https://github.com/NixOS/nixpkgs/blob/dce77eb2493e86e96326364a78b82ae233508aae/pkgs/development/ocaml-modules/pyml/default.nix

**Comment by UnixJunkie** [comment]
@quinn-dougherty you can close this issue then
