### ISSUE TITLE
BSDs not considered in pyml_arch.ml.c

### ISSUE THREAD

**Issue by drchrispinnock** [thierry-martinez/pyml#74]
If __FreeBSD__, __NetBSD__ or __OpenBSD__ are defined, it should be possible to use the same fd_of_int outcome as Mac & Linux.

**Comment by UnixJunkie** [comment]
Maybe you can try a fix on your OS and propose a patch if that solves your problem.

**Comment by thierry-martinez** [comment]
Thank you for the report, and sorry for the so long delay. This should be fixed in a7c8da4.

**Comment by drchrispinnock** [comment]
Hi @thierry-martinez - unfortunately on at least one of them (NetBSD), unix does not seem to be defined. __unix__ is. I've successfully build pyml today on NetBSD by also checking for __unix__ in pyml_arch.ml.c
