### ISSUE TITLE
how to make pyml aware of a single python "module"

### ISSUE THREAD

**Issue by UnixJunkie** [thierry-martinez/pyml#77]

**Comment by UnixJunkie** [comment]
Sorry, I am writing a proper question now...

**Comment by UnixJunkie** [comment]
If I have a python "module". I.e. I wrote a couple of functions into a Python file.
Let's say toto.py.
What is the proper way to make pyml aware of this Python module?
My plan is for my ocaml program to just call functions from this module, which would have done all the imports it needs and such.
Do I have to install this toto.py file? How (using pip?) and where should it be installed?
Sorry if this is a dumb question.

**Comment by UnixJunkie** [comment]
Or, is there a way to say: "please pyml, interprete the toto.py file because then I am going to call functions from it" ?

**Comment by UnixJunkie** [comment]
In pyml_tests.ml there are probably some example bits that I need.

**Comment by thierry-martinez** [comment]
Sorry for the delay. I think that `let toto = Py.Import.import_module "toto"` should do the trick.

**Comment by UnixJunkie** [comment]
Thanks a lot Thierry! You're the best.

**Comment by UnixJunkie** [comment]
I wonder if I can combine this with the ocaml library which allows to statically include a file.
Hence, I would not need to have to install this python file somewhere, it would always be part of my ocaml executable! :)
