### ISSUE TITLE
Py.Initialize() - not allowing process to be killed with Ctrl+C

### ISSUE THREAD

**Issue by ArulselvanMadhavan** [thierry-martinez/pyml#83]
Hello,

I have some code that initializes a server like this
```ocaml
let () = 
  Py.Initialize ()
  launch_server()
```

When I comment out the line Py.Initialize() I am able to kill the server with Ctrl+C but I am not able to do it with this line.

Am I doing something wrong in the way I am using this library?

Thanks!

**Comment by thierry-martinez** [comment]
Thank you for reporting! I never noticed this, but you are right and you don't do anything wrong, and this behavior is indeed annoying. I fixed this in 821651a and it will be part of the next release.

If you want to make your program interruptible with `Ctrl+C` even with the current released version of `pyml`, you may just call `Sys.set_signal Sys.sigint Signal_default` after calling `Py.initialize ()`.
