### ISSUE TITLE
switching back and forth to ipython produces an exception then segfaults

### ISSUE THREAD

**Issue by nilsbecker** [thierry-martinez/pyml#9]
in pymlutop, i `#require "pyml";;Py.initialize ();; Py.Run.ipython ()` . this works and i quit to arrive back in utop. second time still works. third time: `Exception: Py.E (<type 'exceptions.KeyError'>, None)`, no ipython session. fourth time: segfault.

**Comment by thierry-martinez** [comment]
Should be fixed. Thank you for the report. (There is still a bug in Py.Run.eval, I just changed Py.Run.ipython to use Py.Run.simple_string instead. I will try to fix this other bug soon.)

**Comment by thierry-martinez** [comment]
This bug is now fixed cleanly: it was due to a wrong declaration for `PyImport_AddModule` (which borrows the reference it returns).
