### ISSUE TITLE
Py.Dict.find raises Invalid_argument instead of Not_found

### ISSUE THREAD

**Issue by jonathan-laurent** [thierry-martinez/pyml#96]
The `Dict.find` method is supposed to raise `Not_found` when passed an absent key:

https://github.com/thierry-martinez/pyml/blob/ae3d27dc7da593545a8ea9ec7a879c189c0130c2/py.mli#L651-L654

However, it throws `Invalid_argument` instead. I believe this is due to commit af7e79a468d19c5c2a0cf122d59e7854393d29a7, which incorrectly replaces `Pyutils.option_unwrap` by `Option.get`. This bug is currently [breaking](https://github.com/janestreet/ppx_python/blob/94494ecfcc370f403a485f131e5dcb661fff0931/src/ppx_python_conv.ml#L236-L237) `ppx_pythonlib` (@LaurentMazare).

**Comment by thierry-martinez** [comment]
Thanks for reporting these inconsistencies. Sorry for the delay: it should be fixed in 6e72b45. This commit is more than a revert of af7e79a: there were other inconsistencies that predate this commit, and the behavior of all `find` functions is now uniform.
